### ISSUE TITLE
Where are the other files to flash a device?

### ISSUE THREAD

**Issue by JrtPec** [plan-d-io/P1-dongle#1]
The script to flash a device needs files like `boot_app0.bin`, `bootloader_dio_80m.bin` and `P1-dongle-V0.85.ino.partitions.bin` Which I cannot find in the repo. Can you upload these files as well?

**Comment by Epyon01P** [comment]
I've added all necessary and optional files to the [/bin](https://github.com/plan-d-io/P1-dongle/tree/main/bin) directory, and updated the flashing instructions on the [readme](https://github.com/plan-d-io/P1-dongle#readme).
