### ISSUE TITLE
Discovered entities with a name that starts with the device name

### ISSUE THREAD

**Issue by waaslandwolf** [plan-d-io/P1-dongle#14]
Since doing an upgrade, I receive the following warning in Home Assistant for the P1 dongle device:

Discovered entities with a name that starts with the device name

This stops working in version 2024.2.0. Please address before upgrading.

Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped off the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

    sensor.p197af50_reboots
    sensor.utility_meter_total_consumption_t2
    sensor.p197af50_free_heap_size
    sensor.p197af50_min_free_heap
    sensor.cofyaf50_firmware
    sensor.utility_meter_voltage_phase_2
    sensor.utility_meter_total_consumption_t1
    sensor.cofyaf50_last_reset_reason
    sensor.utility_meter_current_phase_1
    sensor.cofyaf50_syslog
    sensor.utility_meter_active_power_consumption
    sensor.utility_meter_text_message
    sensor.cofyaf50_reboots
    sensor.cofyaf50_min_free_heap
    sensor.utility_meter_maximum_demand_current_month
    sensor.p197af50_ip
    sensor.cofyaf50_free_heap_size
    sensor.utility_meter_total_active_power
    sensor.p197af50_last_reset_reason
    sensor.cofyaf50_max_allocatable_block
    sensor.utility_meter_voltage_phase_1
    sensor.utility_meter_natural_gas_consumption
    sensor.p197af50_max_allocatable_block
    sensor.p197af50_last_reset_reason_verbose
    switch.p197af50_reboot
    sensor.cofyaf50_last_reset_reason_verbose
    sensor.utility_meter_current_average_demand
    sensor.p197af50_syslog
    sensor.utility_meter_total_energy_injected
    sensor.utility_meter_current_phase_3
    sensor.p197af50_firmware
    sensor.utility_meter_total_injection_t2
    sensor.utility_meter_active_power_injection
    sensor.cofyaf50_ip
    sensor.utility_meter_active_tariff_period
    sensor.utility_meter_total_injection_t1
    sensor.utility_meter_current_phase_2
    sensor.utility_meter_voltage_phase_3
    switch.cofyaf50_reboot
    sensor.utility_meter_total_energy_consumed

Home Assistant: Installed version 2023.8.3 
P1 Dongle: INFO: Digital meter dongle COFYAF50 V1.08 by plan-d.io

**Comment by Epyon01P** [comment]
Fixed with version 2.x
