### ISSUE TITLE
Total active power no longer updated

### ISSUE THREAD

**Issue by michaelpiron** [plan-d-io/P1-dongle#16]
Since 20minutes ago, the dongle stopped publishing "total_active_power" values, whereas "active_power_consumption" & "active_power_production" continue to be updated.

MQTT log:
data > devices > utility_meter has no "total_active_power" topic anymore:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/4d8d9a7e-d957-4e94-81f9-7f1bf89f2ec1)

Sensor "active_power_injection" still being updated:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/dfff2929-95a6-42ea-a2f4-64eef1a8429e)

Sensor "total_active_power" stopped being updated:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/544db42f-794e-414d-9f59-a67c87e949ac)

**Comment by michaelpiron** [comment]
A few minutes later, the "total_active_power" topic has appeared again in the MQTT log, and the HA sensor is again being updated:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/5140ac87-beca-4536-89bd-6b1cd7c363db)

There has been a gap for 23 minutes:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/4a49f808-dc2b-4c6e-8f5e-74728970b5a1)


What could be causing this?

**Comment by Epyon01P** [comment]
I believe the spurious reading detection is acting up again. Which release channel are you on? This should be fixed on the develop channel.

**Comment by michaelpiron** [comment]
I’m on dev channel, and have been on version 2.22 when the issue happened:

![IMG_3627](https://github.com/plan-d-io/P1-dongle/assets/4469877/da031954-d597-40c6-a4ab-713310a80ecc)

**Comment by jantielens** [comment]
Same here. For a couple of weeks, the "Total active power" value "gets stuck" randomly, and for some random time. 
![image](https://github.com/plan-d-io/P1-dongle/assets/9884103/b9878995-a776-4229-95cd-63922b33741a)

**Comment by Epyon01P** [comment]
Thx, very helpful. This is due the way the dongle currently blanks invalid readings received from the meter. I will overhaul the whole function to also fix #15 .

**Comment by Epyon01P** [comment]
Pushed a (long overdue) fix to dev. Should also fix #15 .
The issue had to do with negative values (injection) being incorrectly flagged as invalid. This slipped through my testing routine (I don't have solar panels).

**Comment by Epyon01P** [comment]
Fixed in V2.23.

**Comment by maxhelskens** [comment]
I am not sure if this is the same issue, but I constantly get the following syslog message:

```
WARNING: Spurious value for DSMR key 1-0:2.8.2: 0.01, 2, 1
```

The log is always about key 2.8.2.

Multiple HA entities remain unknown and the other entities do not always update.

<img width="242" alt="Screenshot 2024-11-06 at 16 28 32" src="https://github.com/user-attachments/assets/03ca4b8d-000a-4088-bbc8-0abe8d83e30f">

I have Firmware version 2.23 installed.
