### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by JrtPec** [plan-d-io/P1-dongle#17]
Today I set down with a colleague of mine who uses a Mac and we tried flashing a P1-dongle. I updated the Flashing Instructions on the Wiki accordingly, but for some reason Github doesn't allow you to make a PR for wikis.

So here it is: https://github.com/plan-d-io/P1-dongle/compare/main...JrtPec:P1-dongle:master?expand=1

@Epyon01P could you update the wiki?

**Comment by Epyon01P** [comment]
Thanks for the additions. Merged!
