### ISSUE TITLE
What does a blue flashing light mean?

### ISSUE THREAD

**Issue by JrtPec** [plan-d-io/P1-dongle#2]

**Comment by Epyon01P** [comment]
Both the LED colour and behaviour have meanings
**Colour**
Red: booting or critical error
Green: joining wifi or wifi not configured (access point mode)
Blue: connected to wifi
**Behaviour**
Continuous: no errors
Flashing: error (no digital meter connected and/or MQTT broker configured but not reachable)

E.g. flashing green means no digital meter connected while in access point mode, flashing blue means no digital meter connected and/or cannot reach broker while being connected to wifi.

Will add this info to the wiki eventually.

**Comment by Epyon01P** [comment]
LED signal meaning added to the [wiki](https://github.com/plan-d-io/P1-dongle/wiki/Basic:-LED-signals).
