### ISSUE TITLE
Support for WPA2 Enterprise EAP-TTLS

### ISSUE THREAD

**Issue by mcuelenaere** [plan-d-io/P1-dongle#7]
I noticed [in the code](https://github.com/plan-d-io/P1-dongle/blob/main/P1-dongle.ino#L180) that currently only WPA/WPA2 Personal support is available.

Having support for WPA2 Enterprise EAP-TTLS would be really useful for certain usecases (read as: [support Telenet Wi-Free](https://www2.telenet.be/nl/klantenservice/wat-is-telenet-wi-free/)).

Based on some quick searching through the ESP32 code, this seems to be [a supported usecase](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/examples/WiFiClientSecureEnterprise/WiFiClientSecureEnterprise.ino#L61-L64) and not too difficult to add support for.

I might look into adding support myself, if I get my hands on a dongle. If not, this issue can be used by someone else as a starting point to implement it.

**Comment by Epyon01P** [comment]
I have not identified a clear use case for this, especially now WiF-Free is being shut down. If your digital meter is outside wifi coverage, perhaps you can take a look at my [LoRa dongle](https://github.com/plan-d-io/P1-LoRa-receiver).
